server:
  error:
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:mysql://200.128.9.179:3306/alugadora?createDatabaseIfNotExist=true
    #url: jdbc:mysql://10.28.0.35:3306/locadoradecarro?createDatabaseIfNotExist=true
    username: remoto
    password: remoto
  jpa:
    hibernate:
      ddl-auto: update